#!/usr/bin/env python3
"""Stop-hook worker: (re)write docs/code/<path>.md for every code file whose content changed.

Called by document-code.sh after each turn; can also be run by hand: python3 .claude/hooks/code_docs.py
A doc records the sha256 of the source it was written from, so a file is only re-documented when
its content changes (by Claude, by Roman, or by a git checkout). Standard library only.
"""
import fcntl
import hashlib
import os
import re
import subprocess
import tempfile
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime
from pathlib import Path

PROJECT = Path(os.environ.get("CLAUDE_PROJECT_DIR", Path(__file__).resolve().parents[2]))
DOCS_DIR = PROJECT / "docs" / "code"
STATE_DIR = PROJECT / ".claude" / "code-docs"
AGENT_FILE = PROJECT / ".claude" / "agents" / "code-documenter.md"
CODE_EXTENSIONS = {".py", ".sh", ".sql", ".json", ".yaml", ".yml", ".toml", ".js", ".ts"}
SKIP_PREFIXES = ("docs/", "learning/")
MAX_SOURCE = 60_000  # characters of source sent to the model
HEADER = re.compile(r"<!-- generated by \.claude/hooks/code_docs\.py from (\S+) \(sha256 ([0-9a-f]{64})\)")


def log_run(msg: str) -> None:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    with open(STATE_DIR / "runs.log", "a", encoding="utf-8") as f:
        f.write(f"{datetime.now().isoformat(timespec='seconds')} {msg}\n")


def code_files() -> list[str]:
    """Tracked and untracked-but-not-ignored files (so .env and .venv never appear), filtered to code."""
    out = subprocess.run(["git", "ls-files", "--cached", "--others", "--exclude-standard"],
                         cwd=PROJECT, capture_output=True, text=True, check=True).stdout
    return sorted(p for p in out.splitlines()
                  if Path(p).suffix in CODE_EXTENSIONS and not p.startswith(SKIP_PREFIXES)
                  and (PROJECT / p).is_file())


def doc_path(src: str) -> Path:
    # ".claude/hooks/x.py" -> docs/code/_claude/hooks/x.py.md (hidden folders would hide the docs)
    parts = [("_" + p[1:]) if p.startswith(".") else p for p in Path(src).parts]
    return DOCS_DIR.joinpath(*parts).with_name(parts[-1] + ".md")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def documented_hash(doc: Path) -> str | None:
    if not doc.exists():
        return None
    m = HEADER.search(doc.read_text(encoding="utf-8"))
    return m.group(2) if m else None



def private_rules() -> str:
    """The privacy section of private/CONTEXT.md (gitignored, local only), if it exists.
    The agent runs without tools, so it can't read the file itself; its rules go into the prompt."""
    path = PROJECT / "private" / "CONTEXT.md"
    if not path.is_file():
        return ""
    m = re.search(r"^## Privacy section.*?(?=^## |\Z)", path.read_text(encoding="utf-8"), flags=re.M | re.S)
    return f"\n\n---\nPRIVATE RULES (local only; follow them, never quote them):\n{m.group(0)}" if m else ""


def build_prompt(src: str, doc: Path) -> str:
    instructions = re.sub(r"\A---.*?---\s*", "", AGENT_FILE.read_text(encoding="utf-8"), count=1, flags=re.S)
    instructions += private_rules()
    source = (PROJECT / src).read_text(encoding="utf-8", errors="replace")[:MAX_SOURCE]
    numbered = "\n".join(f"{i:4} | {line}" for i, line in enumerate(source.splitlines(), 1))
    previous = doc.read_text(encoding="utf-8") if doc.exists() else "(none: first version)"
    decisions = PROJECT / "DECISIONS.md"
    titles = "\n".join(re.findall(r"^### .+$", decisions.read_text(encoding="utf-8"), flags=re.M)) \
        if decisions.exists() else "(none)"
    index = PROJECT / "learning" / "INDEX.md"
    notes = "\n".join(l for l in index.read_text(encoding="utf-8").splitlines() if l.startswith("- ")) \
        if index.exists() else "(none)"
    root = os.path.relpath(PROJECT, doc.parent).replace(os.sep, "/") + "/"
    others = "\n".join(f"- {f} -> {os.path.relpath(doc_path(f), doc.parent)}" for f in code_files() if f != src)
    return (f"{instructions}\n\n---\nToday's date: {datetime.now():%Y-%m-%d}\n"
            f"File: {src}\nRelative path from the doc to the repo root (<root>): {root}\n\n"
            f"DECISIONS.md titles:\n{titles}\n\nlearning/INDEX.md:\n{notes}\n\n"
            f"Other code files and their docs (relative to this doc):\n{others or '(none)'}\n\n"
            f"---\nPREVIOUS DOC:\n{previous}\n\n---\nSOURCE ({src}):\n{numbered}\n\n"
            "---\nReturn the doc body now, starting with the Summary line.")


def document(src: str) -> str:
    doc = doc_path(src)
    digest = sha256(PROJECT / src)
    env = {**os.environ, "DECISION_LOGGER_CHILD": "1"}  # the child session must not trigger hooks again
    with tempfile.TemporaryDirectory() as tmp:  # run outside the repo so project CLAUDE.md isn't loaded
        proc = subprocess.run(
            ["claude", "-p", "--model", "sonnet", "--tools", "",
             "--settings", '{"disableAllHooks": true}', "--no-session-persistence"],
            input=build_prompt(src, doc), capture_output=True, text=True, cwd=tmp, env=env, timeout=400,
        )
    out = proc.stdout.strip()
    if proc.returncode != 0 or not out.startswith("Summary:"):
        return f"error {src}: exit {proc.returncode}: {(proc.stderr or out)[:300]!r}"
    summary, _, body = out.partition("\n")
    doc.parent.mkdir(parents=True, exist_ok=True)
    doc.write_text(
        f"# `{src}`\n\n<!-- generated by .claude/hooks/code_docs.py from {src} (sha256 {digest}) "
        f"on {datetime.now():%Y-%m-%d}; don't edit by hand, it's rewritten when the file changes -->\n\n"
        f"> {summary.removeprefix('Summary:').strip()}\n\n{body.strip()}\n", encoding="utf-8")
    return f"ok {src}"


def write_index() -> None:
    rows = []
    for doc in sorted(DOCS_DIR.rglob("*.md")):
        if doc.name == "README.md":
            continue
        text = doc.read_text(encoding="utf-8")
        m, summary = HEADER.search(text), re.search(r"^> (.+)$", text, flags=re.M)
        if m:
            rows.append(f"| [`{m.group(1)}`]({doc.relative_to(DOCS_DIR).as_posix()}) | "
                        f"{summary.group(1) if summary else ''} |")
    (DOCS_DIR / "README.md").write_text(
        "# Code docs\n\nOne doc per code file, explaining every part of it. Written automatically by the "
        "`code-documenter` agent (Stop hook `.claude/hooks/document-code.sh`) whenever a file's content "
        "changes. Don't edit by hand. Decisions are in [DECISIONS.md](../../DECISIONS.md); concepts and "
        "sources are in [learning/](../../learning/INDEX.md).\n\n| File | What it is |\n|---|---|\n"
        + "\n".join(rows) + "\n", encoding="utf-8")


def main() -> None:
    if (STATE_DIR / "disabled").exists():
        log_run("skip: disabled")
        return
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    with open(STATE_DIR / "lock", "w") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)  # overlapping turns wait, then find the work already done
        files = code_files()
        stale = [f for f in files if documented_hash(doc_path(f)) != sha256(PROJECT / f)]
        live = {doc_path(f) for f in files}
        removed = [d for d in DOCS_DIR.rglob("*.md") if d.name != "README.md" and d not in live
                   and HEADER.search(d.read_text(encoding="utf-8"))] if DOCS_DIR.exists() else []
        for d in removed:
            d.unlink()
        if not stale and not removed:
            log_run("ok: nothing changed")
            return
        with ThreadPoolExecutor(max_workers=3) as pool:
            results = list(pool.map(document, stale))
        write_index()
        log_run("; ".join(results + [f"removed {d.relative_to(DOCS_DIR)}" for d in removed]))


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # never break the session because of docs
        log_run(f"error: {type(exc).__name__}: {exc}")
